apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: default
  labels:
    app: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - name: locust
        image: locustio/locust:latest
        ports:
        - containerPort: 8089
          name: web-ui
        - containerPort: 5557
          name: master-p1
        - containerPort: 5558
          name: master-p2
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: LOCUST_MODE
          value: "master"
        - name: TARGET_HOST
          value: "http://do-sample-app-service:8080"
        volumeMounts:
        - name: locustfile
          mountPath: /home/locust
      volumes:
      - name: locustfile
        configMap:
          name: locust-script
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: default
  labels:
    app: locust-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - name: locust
        image: locustio/locust:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: LOCUST_MODE
          value: "worker"
        - name: LOCUST_MASTER_NODE_HOST
          value: "locust-master-service"
        - name: TARGET_HOST
          value: "http://do-sample-app-service:8080"
        volumeMounts:
        - name: locustfile
          mountPath: /home/locust
      volumes:
      - name: locustfile
        configMap:
          name: locust-script
---
apiVersion: v1
kind: Service
metadata:
  name: locust-master-service
  namespace: default
  labels:
    app: locust-master
spec:
  type: LoadBalancer
  selector:
    app: locust-master
  ports:
  - name: web-ui
    protocol: TCP
    port: 8089
    targetPort: 8089
  - name: master-p1
    protocol: TCP
    port: 5557
    targetPort: 5557
  - name: master-p2
    protocol: TCP
    port: 5558
    targetPort: 5558
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-script
  namespace: default
data:
  locustfile.py: |
    from locust import HttpUser, task, between
    import json
    import random

    class BlogUser(HttpUser):
        wait_time = between(1, 3)
        
        @task(3)
        def view_posts(self):
            """Simula usuarios viendo el blog"""
            self.client.get("/")
        
        @task(1)
        def create_post(self):
            """Simula usuarios creando posts"""
            titles = [
                "My First Post",
                "Learning Kubernetes",
                "Autoscaling with HPA",
                "Load Testing with Locust",
                "DevOps Best Practices",
                "Microservices Architecture",
                "Cloud Native Applications",
                "Container Orchestration"
            ]
            
            contents = [
                "This is a test post to generate load on the application.",
                "Kubernetes is amazing for orchestrating containers at scale.",
                "Horizontal Pod Autoscaler helps maintain application performance.",
                "Locust is a great tool for load testing web applications.",
                "Implementing proper monitoring is crucial for production systems.",
                "Breaking down monoliths into microservices improves scalability.",
                "Cloud native apps are designed to leverage cloud computing benefits.",
                "Container orchestration automates deployment and scaling."
            ]
            
            payload = {
                "title": random.choice(titles) + f" #{random.randint(1, 1000)}",
                "content": random.choice(contents)
            }
            
            self.client.post(
                "/submit",
                data=json.dumps(payload),
                headers={"Content-Type": "application/json"}
            )
